project_id = "qxennwcuuhahkkjyleuy"

[functions.grade-essay]
verify_jwt = false

[functions.analyze-speaking]
verify_jwt = false

[functions.send-weekly-report]
verify_jwt = false

[functions.reading-test]
verify_jwt = false

[functions.listening-test]
verify_jwt = false
